### ISSUE TITLE
React Native CameraRoll.getPhotos API doesn't seem to return

### ISSUE THREAD

**Issue by afashaisakiye** [react-native-community/react-native-cameraroll#167]
# Question
For some reason, I have failed to get images data from CameraRoll.getPhtos. 
Here is my code
```
import React,{useState, useEffect} from 'react';
import {View} from 'react-native';
import * as Permissions from 'expo-permissions';
import CameraRoll from "@react-native-community/cameraroll";

const getImages = async (setImages) => {
   await Permissions.askAsync(Permissions.CAMERA_ROLL);
   const x=await CameraRoll.getPhotos({first:2})
   await setImages([...x.edges])
}

export default function App() {
  const [images,setImages]=useState([])
  useEffect(() => {
    console.log('loading photos')
    getImages(setImages)
    console.log('done')
    console.log(images)
  }, []);
  return (
    <View >
    </View>
  );
} 
```
The code is intended to load images into the state when the component mounts. How can I fix this problem?
Link to question on Stack Overflow ([Link](https://stackoverflow.com/questions/61608955/react-native-cameraroll-getphotos-api-doesnt-seem-to-return))

**Comment by bartolkaruza** [comment]
Hey there, thanks for posting. This looks like a question about React state management to me. I see you also already posted it on Stack Overflow, which seems like the right place for this type of question. I'm going to close the issue here because it's not directly related to cameraroll. If you find a defect, specific to this library, let me know and I'll reopen the issue.
